version: '3'
services:
  app:
    image: fetch-backend-exercise-app:latest
    ports:
      - 8800:8800
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - APP_HOST=app
